apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: golang-server
  labels:
    app: golang-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-server
  template:
    metadata:
      labels:
        app: golang-server
    spec:
      containers:
      - name: golang-server
        image: gabrieldpadua21/golang-server:latest
        ports:
        - containerPort: 8080